server:
  port: 8080

spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/piclibrary
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.zhige.library.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 到控制台
